### ISSUE TITLE
Issue with spack-based R installation

### ISSUE THREAD

**Issue by smjenness** [statnet/computing#3]
@sgoodreau @dth2 @andsv2 : please note that due to a potential bug in the Spack package manager (https://github.com/spack/spack/issues/12915), the default method for loading on Mox has required an update. Details are on the README here: https://github.com/statnet/computing/tree/master/build. 

1. I have moved the default location of the spack to `gscratch/csde/spack`, so spack load paths in your `loadR.sh` must be updated.
2. You must (for the time being) manually specify the spack module file location.

**Comment by smjenness** [comment]
Please let any of your other users who use this spack-based approach know about these changes.

**Comment by dth2** [comment]
When trying to load R using spack I get the following: 

[dth2@n2232 ~]$ source ~/loadR.sh
==> Error: No compilers for operating system centos7 satisfy spec gcc@9.2.0

No idea what this means.

**Comment by smjenness** [comment]
@dth2 This is likely an unrelated issue. If you are still having problems, please open another issue.
