### ISSUE TITLE
Bad link for building R packages on Wiki

### ISSUE THREAD

**Issue by martinamorris** [statnet/computing#4]
Right now the R packages link on this page just points to "build a new page".  I suspect the link just needs to be changed to the R packages link on the right hand list.

https://github.com/statnet/computing/wiki

**Comment by smjenness** [comment]
@andsv2 Can you update this page when you get a chance? I think you can just mostly point to this page: https://github.com/statnet/computing/tree/master/build

**Comment by martinamorris** [comment]
It may be that the link just needs to be updated to point to the existing instructions on the wiki page (listed on the right nav):

https://github.com/statnet/computing/wiki/Building-R-Packages-on-Hyak

As long as those are up to date.
